== Overview

Let's take a quick conceptual look at *HellHound Systems*.


=== Execution model
Systems composed by [*Components*]. A system knows how to start and stop components. It is also
responsible for managing dependencies between theme. Components are the smallest parts of a system whic are reusable.

.A very basic schema of a System
image::system.svg[A very basic schema of a System, align="center"]


A *HellHound* system is basically a `map` describing different aspects of a program. Each program might have several
systems. For example a development system and a production system. But there would be just a system running at a given
time.

Systems should follow a certain spec (`:hellhound.system/system`). For example any system should have a`:components` key
with a vector as its value. All the ``components``of the system should be defined under this key. Each component is a `map`
describing the behaviours of that component (For more info on components read [here](./Components.md)).

In order to use *HellHound* systems. First you need to define your system by defining a map with at least one key. Yupe,
you guessed it correctly, the `:components` key. We're going to discuss the system's keys in bit. So for now just let's
talk about how to start and stop a system.

After defining the system. The next step would be to set the defined system as the default system of your program by using
`hellhound.system/set-system!` function. This function accepts just one argument which is the system map. It basically
analayze the given map and set it as the default system of the program. From now on, you can call `hellhound.system/start`
and `hellhound.system/stop` function.

Basic execution flows of a system are `start` and `stop`. Both of them creates a graph from the system components and their
dependencies. Then they `start`/`stop` the system by walking through that graph and calling the `start-fn` and `stop-fn`
function of each component.

After starting a system, you can access the running system via `hellhound.system/system` function. It would returns a map
describing the current running system including all the running components.

There are two ways to manage dependencies in your components code. The first one via a the system map itself, by treating
the system map as a repository of dependencies. The second way is via dependency injection model which is not supported
at this version (`v1.0.0`). Anyway, any component can pull what ever it needs from the system map by calling
`hellhound.system/get-component` function and passing the component name to it. This function will simply look for the
component in system map and returns the running component map. There is a huge problem with this apparoach. By using this
apparoach components knows too much about the environment around them, so it reduce their portablity.

[NOTE]
====
In near future we're going to add the support for dependency injection to *HellHound* systems.
====

.A schema of components of a system and how they might depends on each other
image::system-deps.svg[A schema of components of a system and how they might depends on each other, align="center"]

=== Workflow
System's workflow describes the dataflow of the system. It describes where data comes in and where information goes out of
the system. By "where" I mean which component of the system. As mentioned before each *HellHound* [Component](./Components.md)
has an *input stream* and an *output stream* assigned to them. You can think of each component as a pipe, the whole
system as a pipeline. Data flows to this pipeline based on your piping (description) from entry points and exits the pipeline
from exit points. Pipeline might have more than one entry or exit points or none at all.

.Components process the input stream and produce the output put stream
image::component-io.svg[Components process the input stream and produce the output put stream, align="center"]

Using the system workflow you can design an open or a close dataflow for your system. A Close system is a type of system
which all of its components have their *input* and *output* connected. In the other hand, an open system is a type of
system which *NOT* all of the *inputs* and *outputs* of components connected to each other.

.Open system on the left and Close system on the right
image::workflow-types.svg[Open system on the left and Close system on the right, align="center"]

[IMPORTANT]
.Don't confuse Input and Output of each component which components dependencies.
====
====

Components of a system should consum from their `INPUT` and produce their `OUTPUT` in non-blocking fashion in order to avoid
blocking in a system.

Check out the [workflow](./Workflow.md) section for more information.
