require 'webrick'
require 'asciidoctor'

desc 'Run doc webserver'
task :serve do
  root = File.expand_path './_build/'
  `cp images ./_build/ -rv`
  server = WEBrick::HTTPServer.new Port: 3000, DocumentRoot: root
  trap 'INT' do server.shutdown end
  server.start
end

desc 'deploy the docs'
task :deploy do
  Asciidoctor .convert_file(
    'index.adoc', to_dir: '_build/', mkdirs: true, safe: :safe,
    backend: :html5, header_footer: true, sourcemap: true,
    stylesdir: 'stylesheets',
    base_dir: './',
    attributes: {
      'stylesdir' => 'styles',
      'imagesdir' => './images',
      'nofooter' => true,
      'stylesheet' => 'style.css'
    })

  system("cp ./CNAME ./_build/CNAME")
  system("cd ../..")
  system("git branch -D gh-pages")
  system("git checkout --orphan gh-pages")
  system("cp -rv docs/guides/_build/ ./build/")
  system("git rm -rf ./")
  system("cp -r build/* ./ ")
  system("git add .")
  system("git commit -a -m \"Release at #{Time.now.utc}\"")
  system("git push origin gh-pages -f")
  system("git checkout master")
end

task default: :serve
