[appendix]
= Prerequisite
Before learning more about *HellHound* and how to use it, you need to know about several concepts and libraries in advance
which are heavily used in *HellHound*. If you already know about tools and concepts such as Manifold, Deffered and Stream
just skip to <<_getting_started,Getting Started>> section, Otherwise please read this section first.

== Commander Pattern
Have you ever hit a wall with REST? Does modeling your problem-domain into CRUD-able entities feel like fitting
a square peg into a round hole? Perhaps, instead of modeling our services like little databases, we should instead
model them like reactors over immutable event streams.

Commander pattern is an application architecture design pattern. In order to know more
about the concept, it is highly recommend to watch this https://www.youtube.com/watch?v=B1-gS0oEtYc[video].

HellHound heavily inspired from this pattern.

== Manifold
[NOTE]
====
Most of the documentation about Manifold library have been taken and from it's official documentation and modified
to make the life of the user easier. Kudos to the authors of Manifold.
====

This library provides basic building blocks for asynchronous programming, and can be used as a translation layer
between libraries which use similar but incompatible abstractions. Manifold provides two core abstractions:
*deferreds*, which represent a single asynchronous value, and *streams*, which represent an ordered sequence
of asynchronous values.

*HellHound* uses manifolds almost everywhere, so it's a good idea learn about this fantastic library which is brought to us
by https://github.com/ztellman[@ztellman] and the awesome https://github.com/ztellman/manifold/graphs/contributors[contributors]
of this library.

Long story short, *Manifold* library provides awesome asynchronous values by *deferreds* and a super useful abstraction
for **streams**.

[NOTE]
=====
If you're interested in Manifold, you might want to know about the http://aleph.io/manifold/rationale.html[rationale] behind it.
=====

include::deferred.adoc[]

include::stream.adoc[]
