= Prerequisite
Before learning more about *HellHound* and how to use it, you need to know about several concepts and libraries in advance
which are heavily used in *HellHound*. If you already know about these concepts in the following topics, you can easily skip
this chapter and jump to [Getting Started](../getting_started/README.md) guide.

== Commander Pattern
Have you ever hit a wall with REST? Does modeling your problem-domain into CRUD-able entities feel like fitting
a square peg into a round hole? Perhaps, instead of modeling our services like little databases, we should instead
model them like reactors over immutable event streams.

Commander pattern is an application architecture design pattern which is used to build *HellHound*. In order to know more about the concept, it is highly recommend
to watch this https://www.youtube.com/watch?v=B1-gS0oEtYc[video].




== Manifold
---
This library provides basic building blocks for asynchronous programming, and can be used as a translation layer
between libraries which use similar but incompatible abstractions. Manifold provides two core abstractions:
*deferreds*, which represent a single asynchronous value, and *streams*, which represent an ordered sequence
of asynchronous values.

*HellHound* uses manifolds almost everywhere, so it's a good idea learn about this fantastic library which is brought to us
by https://github.com/ztellman[@ztellman] and the awesome https://github.com/ztellman/manifold/graphs/contributors[contributors]
of this library.

Long story short, *Manifold* library provides awesome asynchronous values by *deferreds* and a super useful abstraction
for **streams**.

[NOTE]
=====
If you're interested in Manifold, you might want to know about the http://aleph.io/manifold/rationale.html[rationale] behind it.
=====

include::deferred.adoc[]

include::stream.adoc[]
