[appendix]
= Contributing to HellHound

Wow, thanks for your interest in helping out with HellHound. Let this document
serve as your guide.

== Looking for work?

If you're looking for a task to work on, check out the
http://github.com/Codamic/hellhound/issues?labels=TODO[TODO] in our issues.

Less defined tasks will be marked with the
http://github.com/Codamic/hellhound/issues?labels=discuss[discuss label]. Jump in here if you want to be
a part of something big.

== New Features

HellHound is the thinking persons framework, so every contribution starts with
some *deeeep* thought. Finished?

Alright, your next step is to start a discussion.

Create an https://github.com/Codamic/hellhound/issues/new[issue] to start
a conversation. Tell us what you're trying to accomplish and how you think you
might do it. If all is well, we'll probably give you the :thumbsup: to
start developing.

== Bugs

Of course, if you run into any straight-up bugs or weirdness feel free to skip
the thinking (or at least too much of it) and immediately submit an https://github.com/codamic/hellhound/issues/new[issue].


We have an issue template in place that will ask you some details
about the platform you are running and how to reproduce the bug. (If
you can reproduce it reliably. If not, go ahead and file the issue
anyway so we can start looking at it.)

Some of the usual stuff we'll want to know:

* What happened?
  ** "I manifested a being from the outer dimensions."
* What did you expect to happen?
  ** "Hello, world."
* How can you reprodice it?
  ** "I created a new HellHound service with the template, then installed some code that Bob Howard gave me."
* What operating system and version are you using?
  ** e.g. "OS X 10.8"
* What version of Clojure, Java, and Leiningen or Boot are you using?
  ** e.g. "Leiningen 2.5.2 on Java 1.8.0_u40 Java HotSpot(TM) 64-Bit Server VM"
* What HellHound version are you using?
  ** e.g. "0.5.0"
  ** or, for a SNAPSHOT: "0.5.1-SNAPSHOT at d0cf2b4"

Even better, include a link to a gist or repository where we can jump straight
to the problem.

== Tests
<PLACEHOLDER TEXT>
